resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'

files(
		'carcols.meta'
		'carvariations.meta'
		'dispatch.meta'
		'gameconfig.xml'
		'global.gxt2'
		'handling.meta'
		'peds.meta'
		'popcycle.dat'
		'popgroups.ymt'
		'vehiclelayouts_armadillo.meta'
		'vehiclelayouts_factionpack.meta'
		'vehiclemodelsets.meta'
		'vehicles.meta'
)

data_file 'CARCOLS_FILE' 'carcols.meta'
data_file 'CARVARIATIONS_FILE' 'carvariations.meta'
data_file 'DISPATCH_FILE' 'dispatch.meta'
data_file 'GAMECONFIG_FILE' 'gameconfig.xml'
data_file 'GLOBAL_FILE' 'global.gxt2'
data_file 'HANDLING_FILE' 'handling.meta'
data_file 'PEDS_FILE' 'peds.meta'
data_file 'POPCYCLE_FILE' 'popcycle.dat'
data_file 'POPGROUPS_FILE' 'popgroups.ymt'
data_file 'VEHICLELAYOUTS_ARMADILLO_FILE' 'vehiclelayouts_armadillo.meta'
data_file 'VEHICLELAYOUTS_FACTIONPACK_FILE' 'vehiclelayouts_factionpack.meta'
data_file 'VEHICLEMODELSETS_FILE' 'vehiclemodelsets.meta'
data_file 'VEHICLES_FILE' 'vehicles.meta'